config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  authenticated :user do
    match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  end

  devise_scope :user do
    get '/registration/:token' => 'users#register_form', as: :register
    put '/registration/:token' => 'users#finish_creating', as: :finish
  end

  post 'gateway' => 'gateway#send_message'
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  text         :text
#  project_id   :integer
#  message_type :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  status       :boolean          default(FALSE)
#

class Message < ActiveRecord::Base
  belongs_to :project

  after_create :send_message

  protected

    def send_message
      
    end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                      :integer          not null, primary key
#  name                    :string(255)
#  site                    :string(255)
#  email                   :string(255)
#  phone                   :string(255)
#  email_on                :boolean
#  sms_on                  :boolean
#  email_template          :text
#  sms_template            :text
#  last_sent               :datetime
#  sent_in_row             :integer
#  created_at              :datetime
#  updated_at              :datetime
#  email_sender_email      :string(255)
#  email_sender            :string(255)
#  email_subject           :string(255)
#  sms_from                :string(255)
#  bitrix_on               :boolean
#  bitrix_url              :string(255)
#  bitrix_login            :string(255)
#  bitrix_password         :string(255)
#  bitrix_title_template   :string(255)
#  bitrix_comment_template :string(255)
#  bitrix_params_template  :string(255)
#  plain_site              :string(255)
#  bitrix_assigned_id      :integer
#

require 'net/http'
require 'json'

class Project < ActiveRecord::Base

  has_many :messages

  def push_lead_to_bitrix(params)
    additional_params = {}
    bitrix_params = JSON.parse self.bitrix_params_template
    bitrix_params.each{|k,v| additional_params[k]=params[v.to_sym] if params[v.to_sym]}

    additional_params[:ASSIGNED_BY_ID] = self.bitrix_assigned_id if !self.bitrix_assigned_id.nil? && self.bitrix_assigned_id > 0

    title = self.bitrix_title_template.gsub(/\{(.*?)\}/) {"#{params[$1.to_sym]}"}
    comment = self.bitrix_comment_template.gsub(/\{(.*?)\}/) {"#{params[$1.to_sym]}"}

    uri = URI("#{self.bitrix_url}crm/configs/import/lead.php")
    params_to_be_sent = { LOGIN: "#{self.bitrix_login}", 
               PASSWORD: "#{self.bitrix_password}", 
               TITLE: "#{title}",
               SOURCE_ID: "#{self.plain_site}",
               NAME: "#{params[:name]}",
               COMMENTS: "#{params[:comment]}",
               PHONE_OTHER: "#{params[:phone]}",
               EMAIL_OTHER: "#{params[:email]}"}.merge(additional_params)
    uri.query = URI.encode_www_form(params_to_be_sent)
    response = Net::HTTP.get(uri)
  end
  handle_asynchronously :push_lead_to_bitrix

end

app/models/sender.rb
class Sender

  class << self

    def send_sms(message)
      project = message.project
      numbers = project.phone.gsub(/\s+/, "").split(",")
      Smsru::API.group_send(  numbers, 
                              message.text, 
                              Settings.sms_api_id, 
                              project.sms_from )
      message.update_columns(status: true)
    end
    handle_asynchronously :send_sms

    def send_email(message)
      project = message.project
      emails = project.email.gsub(/\s+/, "").split(",")
      emails.each do |email|
        UserMailer.custom_mail( email, 
                                project.email_sender_email, "#{project.email_sender} <#{project.email_sender_email}>", 
                                project.email_subject, 
                                message.text )
                              .deliver
      end
      message.update_columns(status: true)
    end
    handle_asynchronously :send_email

  end

end

app/models/settings.rb
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string(255)      not null
#  value      :text
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime
#  updated_at :datetime
#
# Indexes
#
#  index_settings_on_thing_type_and_thing_id_and_var  (thing_type,thing_id,var) UNIQUE
#

class Settings < RailsSettings::CachedSettings
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  accepted               :boolean          default(FALSE)
#  reg_token              :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reg_token             (reg_token) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_token

  def accept
    self.update_column(:reg_token, nil)
    self.update_column(:accepted, true)
  end

  protected

    def generate_token
      self.reg_token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless self.class.exists?(reg_token: random_token)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gateway_controller.rb
class GatewayController < ApplicationController
  protect_from_forgery except: [:send_message]

  def send_message
    proj = Project.where("site LIKE '%?%'", request.referer.split('?').first).first
    return render json: {success: false, site: request.referer} unless proj.present?
    
    # send mail
    if proj.email_on?
      email_text = proj.email_template.gsub(/\{(.*?)\}/) {"#{params[$1.to_sym]}"}
      message = Message.create(project: proj, text: email_text, message_type: "email")
      Sender.send_email(message)
    end

    # send sms
    if proj.sms_on?
      sms_text = proj.sms_template.gsub(/\{(.*?)\}/) {"#{params[$1.to_sym]}"}
      message = Message.create(project: proj, text: sms_text, message_type: "sms")
      Sender.send_sms(message)
    end

    if proj.bitrix_on?
      proj.push_lead_to_bitrix(params)
    end

    render json: {success: true}
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user_by_reg_token

  def register_form
  end

  def finish_creating
    user_params = params.require(:user).permit(:password, :password_confirmation)
    if @user.update(user_params)
      @user.accept
      sign_in(@user)
      redirect_to root_path
    else
      redirect_to register_path(token: @user.reg_token), alert: (@user.errors.full_messages).join("<br/>").html_safe
    end
  end

  protected

    def set_user_by_reg_token
      sign_out(current_user) if current_user
      @user = User.where(reg_token: params[:token]).first
      return render :wrong_token unless @user.present?
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gateway_helper.rb
module GatewayHelper
end

app/views/admin/settings/_mailer_settings.html.erb
<%= simple_form_for :settings, url: admin_settings_update_path, method: :put, html: { class: 'form-horizontal', autocompete: "off" } do |f| %>
  <fieldset>
    <%= f.input :mailer_host, input_html: { value: Settings.mailer_host, autocomplete: 'off' } %>
    <%= f.input :mailer_port, input_html: { value: Settings.mailer_port, autocomplete: 'off' } %>
    <%= f.input :mailer_username, input_html: { value: Settings.mailer_username, autocomplete: 'off' } %>
    <%= f.input :mailer_password, input_html: { value: Settings.mailer_password, autocomplete: 'off' }, as: :string %>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-ok icon-white"></i> Save
    <% end %>
  </fieldset>
<% end %>

app/views/admin/settings/_main_settings.html.erb
<%= simple_form_for :settings, url: admin_settings_update_path, method: :put, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <%= f.input :host, input_html: { value: Settings.host } %>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-ok icon-white"></i> Save
    <% end %>
  </fieldset>
<% end %>

app/views/admin/settings/_sms_settings.html.erb
<%= simple_form_for :settings, url: admin_settings_update_path, method: :put, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <%= f.input :sms_api_id, input_html: { value: Settings.sms_api_id } %>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-ok icon-white"></i> Save
    <% end %>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/register_form.html.erb
Please provide some info to finish registration<br />
<%= flash[:alert] %>
<%= simple_form_for @user, url: finish_path(token: params[:token]), method: :put, html: { class: 'form-horizontal', autocompete: "off" },
wrapper: :horizontal_form,
wrapper_mappings: {
  check_boxes: :horizontal_radio_and_checkboxes,
  radio_buttons: :horizontal_radio_and_checkboxes,
  file: :horizontal_file_input,
  boolean: :horizontal_boolean
} do |m| %>
  <%= m.input :password %>
  <%= m.input :password_confirmation %>
  <%= m.submit %>
<% end %>

app/views/users/wrong_token.html.erb
Wrong registration code! Please contact administrator.